global:
  scrape_interval:     1s
  scrape_timeout:      1s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nvidia_smi_exporter'
    static_configs:
      - targets: ['cj-ai-server.com:9835']


  - job_name: 'nvidia_exporter'
    static_configs:
      - targets: ['cj-ai-server.com:9400']


  - job_name: 'node_exporter_ai_server'
    static_configs:
      - targets: ['cj-ai-server.com:9100']


  - job_name: 'node_exporter_local'
    static_configs:
      - targets: ['localhost:9100']