
volumes:
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

services:

  prometheus:
    image: docker.io/prom/prometheus:v2.55.1
    container_name: prometheus
#    ports:
#      - 9090:9090
    command: "--config.file=/etc/prometheus/prometheus.yaml"
    volumes:
      - ./config/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
      - prometheus-data:/prometheus
    restart: unless-stopped
    network_mode: host   # Use host network

  grafana:
    image: docker.io/grafana/grafana-oss:11.4.0
    container_name: grafana
#    ports:
#      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    restart: unless-stopped
    network_mode: host   # Use host network

  node_exporter:
    image: quay.io/prometheus/node-exporter:v1.8.2
    container_name: node_exporter
    command: "--path.rootfs=/host"
#    ports:
#      - 9100:9100
    pid: host
    restart: unless-stopped
    volumes:
      - /:/host:ro,rslave
    network_mode: host   # Use host network
